version: '3'
services:
  postgres1:
    image: postgres:10.1
    container_name: postgres1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres